import Foundation
@main struct TestRunner {
    static func main() async {
        let devices = Device.parse("List of devices attached\nabc device model:Galaxy_Fold transport_id:1\ndef unauthorized\nghi offline\n* daemon started successfully *\n")
        precondition(devices.count == 3 && devices[0].name == "Galaxy Fold")
        precondition(devices[0].ready && !devices[1].ready && !devices[2].ready)
        print("PASS: device discovery and authorization")
        let frames = ["INFO: Texture: 840x1920", "INFO: Texture: 1920x1840", "INFO: Texture: 1840x1920", "INFO: Texture: 840x1920"].compactMap(FrameSize.parse)
        precondition(frames.count == 4 && frames.first == frames.last && frames[0] != frames[1])
        precondition(FrameSize.parse("INFO: Texture: 0x0") == nil)
        precondition(FrameSize.parse("unrelated 1080x2400") == nil)
        print("PASS: folded, unfolded, rotated and refolded frame parsing")
        let args = Engine.arguments(serial: "USB-123", quality: 1920, audio: false, keyboard: true, top: true)
        precondition(Array(args.prefix(2)) == ["--serial", "USB-123"])
        precondition(args.contains("--no-audio") && args.contains("--keyboard=sdk") && args.contains("--prefer-text") && args.contains("--shortcut-mod=ralt"))
        precondition(!args.contains { $0.contains("crop") || $0.contains("orientation") || $0.contains("new-display") || $0.contains("window-width") })
        print("PASS: mirroring follows device geometry")
        precondition(Wireless.endpoint(" 192.168.0.12:37123 \n") == "192.168.0.12:37123")
        for invalid in ["192.168.0.12", "192.168.0.12:0", "192.168.0.12:65536", "999.1.1.1:1234", "--help", "1.2.3.4:12;echo", "1.2.3.4:-1", "1.2.3:123"] {
            precondition(Wireless.endpoint(invalid) == nil, invalid)
        }
        precondition(Wireless.validCode("012345") && !Wireless.validCode("12345") && !Wireless.validCode("１２３４５６"))
        precondition(Wireless.succeeded("Successfully paired to 192.168.0.12:37123", pairing: true))
        precondition(!Wireless.succeeded("failed to connect to 192.168.0.12:40567", pairing: false))
        precondition(Wireless.succeeded("already connected to 192.168.0.12:40567", pairing: false))
        print("PASS: wireless address, code and ADB response validation")
        precondition(!frames[0].expanded && frames[1].expanded && frames[2].expanded && !frames[3].expanded)
        precondition(!FrameSize(width: 1920, height: 840).expanded)
        print("PASS: fold animation ignores cover-screen rotation")
        let (code, output) = await Engine.run("/bin/sh", ["-c", "read -r value; if [ \"$value\" = 012345 ]; then printf 'Successfully paired to test'; else exit 1; fi"], input: "012345\n")
        precondition(code == 0 && Wireless.succeeded(output, pairing: true))
        precondition(!output.contains("012345"))
        print("PASS: pairing code delivered through stdin without output disclosure")
        precondition(ImageClipboard.focusedPackage("mCurrentFocus=Window{abc u0 com.example.notes/.MainActivity}") == "com.example.notes")
        precondition(ImageClipboard.focusedPackage("mCurrentFocus=null") == nil)
        print("PASS: image paste only targets the original foreground app")
        let fixture = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try! Data([0, 255, 13, 10, 128, 0, 1]).write(to: fixture)
        let (_, expectedHash) = await Engine.run("/usr/bin/shasum", [fixture.path])
        let (binaryCode, actualHash) = await Engine.run("/usr/bin/shasum", [], inputFile: fixture)
        precondition(binaryCode == 0 && actualHash.prefix(40) == expectedHash.prefix(40))
        try! FileManager.default.removeItem(at: fixture)
        print("PASS: binary image stdin remains byte-identical")
    }
}
